import { mkdir, readdir, readFile, unlink, writeFile } from "node:fs/promises"
import { dirname, join, relative, sep } from "node:path"
import {
  type KnowledgeLesson,
  knowledgeIndexFromLessons,
  type LearningCandidate,
  renderKnowledgeLesson,
  renderLearningsMarkdown,
} from "@samskara/core"
import { readToken } from "../config/credentials.js"
import { apiBase } from "../config.js"
import { errorMessage, resolveIo, type Writer } from "../io.js"
import { resolveOption } from "./search.js"

export type LearningRow = {
  readonly id: string
  readonly projectId: string
  readonly audience: "agent" | "human"
  readonly category: string
  readonly title: string
  readonly detail: string
  readonly evidence: ReadonlyArray<{ seq: number; what: string }>
  readonly status: "candidate" | "accepted" | "superseded"
  readonly occurrenceCount: number
}

export type LearnDeps = {
  readonly apiBase: string
  readonly token: string | null
  readonly fetch: typeof globalThis.fetch
  readonly now?: () => Date
  readonly stdout?: Writer
}

export type LearnOptions = {
  readonly project?: string
  readonly audience?: string
  readonly status?: string
  readonly write?: boolean
  readonly out?: string
}

/** Files whose `source:` is one of these URIs belong to `learn --write`; no other file does. */
const GENERATED_SOURCE_PREFIX = "samskara-learning://"

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

const toCandidate = (row: LearningRow): LearningCandidate => ({
  audience: row.audience,
  // Categories are open on the server row and closed in the core union; every category the
  // extractor produces is in the union, so the cast is a formality for rows it produced.
  category: row.category as LearningCandidate["category"],
  title: row.title,
  detail: row.detail,
  evidence: row.evidence,
  fingerprint: row.id,
})

type LessonFrontmatter = {
  readonly title: string
  readonly date: string
  readonly category: string
  readonly tags: ReadonlyArray<string>
  readonly appliesTo: ReadonlyArray<string>
  readonly evidenceCount: number
  readonly audience: string
  readonly source: string | null
}

const parseList = (value: string): ReadonlyArray<string> =>
  value
    .trim()
    .replace(/^\[/, "")
    .replace(/\]$/, "")
    .split(",")
    .map((item) => item.trim().replace(/^["']|["']$/g, ""))
    .filter((item) => item !== "")

/** Frontmatter only, single-line values — the exact shape the house lesson format writes. */
const parseFrontmatter = (content: string): LessonFrontmatter | null => {
  const lines = content.split(/\r?\n/)
  if (lines[0] !== "---") return null
  const end = lines.indexOf("---", 1)
  if (end === -1) return null
  const fields = new Map<string, string>()
  for (const line of lines.slice(1, end)) {
    const at = line.indexOf(":")
    if (at <= 0) continue
    fields.set(line.slice(0, at).trim(), line.slice(at + 1).trim())
  }
  const title = (fields.get("title") ?? "").replace(/^"|"$/g, "")
  const date = fields.get("date") ?? ""
  if (title === "" || date === "") return null
  return {
    title,
    date,
    category: fields.get("category") ?? "uncategorized",
    tags: parseList(fields.get("tags") ?? "[]"),
    appliesTo: parseList(fields.get("applies_to") ?? "[]"),
    evidenceCount: Number.parseInt(fields.get("evidence_count") ?? "0", 10) || 0,
    audience: fields.get("audience") ?? "",
    source: fields.get("source") ?? null,
  }
}

type ExistingLesson = {
  /** Path as the INDEX links it: relative to `.harness/knowledge/`, forward slashes. */
  readonly relPath: string
  readonly frontmatter: LessonFrontmatter
  /** The learning id when this file was generated by `learn --write`; null when hand-written. */
  readonly ownedLearningId: string | null
}

const walkMarkdown = async (dir: string): Promise<ReadonlyArray<string>> => {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => [])
  const files: string[] = []
  for (const entry of entries) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) files.push(...(await walkMarkdown(path)))
    else if (entry.name.endsWith(".md")) files.push(path)
  }
  return files
}

const scanLessons = async (knowledgeDir: string): Promise<ReadonlyArray<ExistingLesson>> => {
  const lessons: ExistingLesson[] = []
  for (const abs of await walkMarkdown(join(knowledgeDir, "lessons"))) {
    const frontmatter = parseFrontmatter(await readFile(abs, "utf8"))
    if (frontmatter === null) continue
    lessons.push({
      relPath: relative(knowledgeDir, abs).split(sep).join("/"),
      frontmatter,
      ownedLearningId: frontmatter.source?.startsWith(GENERATED_SOURCE_PREFIX)
        ? frontmatter.source.slice(GENERATED_SOURCE_PREFIX.length)
        : null,
    })
  }
  return lessons
}

/**
 * `--write` closes the loop: accepted learnings land in the target repo as generated files —
 * LEARNINGS.md for the human reading, one knowledge lesson per learning under
 * .harness/knowledge/ for the agent that reads them next session. The knowledge tree is not
 * ours alone: hand-written lessons stay untouched, and the INDEX is rebuilt from both sets.
 * Files this command generated before (a `samskara-learning://` source in their frontmatter)
 * are pruned the moment their learning leaves the accepted set; nothing else is ever deleted.
 */
export const writeLearnings = async (
  rows: ReadonlyArray<LearningRow>,
  out: { readonly dir: string; readonly projectName: string },
  now: Date,
): Promise<{ readonly written: ReadonlyArray<string>; readonly pruned: ReadonlyArray<string> }> => {
  const knowledgeDir = join(out.dir, ".harness/knowledge")
  const lessonsDir = join(knowledgeDir, "lessons")

  const existing = await scanLessons(knowledgeDir)
  const handWritten = existing.filter((lesson) => lesson.ownedLearningId === null)
  const handWrittenPaths = new Set(handWritten.map((lesson) => lesson.relPath))

  // One lesson per learning: duplicate rows collapse by id, and a regeneration reuses the
  // date already on disk so the slug never churns between runs.
  const unique = new Map<string, LearningRow>()
  for (const row of rows) if (!unique.has(row.id)) unique.set(row.id, row)

  const planned = [...unique.values()].map((row) => {
    const prior = existing.find((lesson) => lesson.ownedLearningId === row.id)
    const date = prior === undefined ? now : new Date(`${prior.frontmatter.date}T00:00:00.000Z`)
    const lesson = renderKnowledgeLesson(toCandidate(row), {
      projectId: row.projectId,
      sourceRef: `${GENERATED_SOURCE_PREFIX}${row.id}`,
      date,
      occurrenceCount: row.occurrenceCount,
    })
    return {
      row,
      path: lesson.path,
      content: lesson.content,
      date: date.toISOString().slice(0, 10),
    }
  })
  const plannedPaths = new Set(planned.map((item) => item.path))

  const pruned: string[] = []
  for (const lesson of existing) {
    if (lesson.ownedLearningId === null) continue
    if (unique.has(lesson.ownedLearningId) && plannedPaths.has(lesson.relPath)) continue
    await unlink(join(knowledgeDir, lesson.relPath))
    pruned.push(`.harness/knowledge/${lesson.relPath}`)
  }

  const written: string[] = []
  const markdown = renderLearningsMarkdown({
    projectName: out.projectName,
    generatedAt: now,
    learnings: [...unique.values()].map(toCandidate),
  })
  await mkdir(lessonsDir, { recursive: true })
  await writeFile(join(out.dir, "LEARNINGS.md"), markdown, "utf8")
  written.push("LEARNINGS.md")

  const indexEntries: KnowledgeLesson[] = handWritten.map((lesson) => ({
    title: lesson.frontmatter.title,
    path: lesson.relPath,
    category: lesson.frontmatter.category,
    appliesTo: lesson.frontmatter.appliesTo,
    tags: lesson.frontmatter.tags,
    evidenceCount: lesson.frontmatter.evidenceCount,
    date: lesson.frontmatter.date,
    audience: lesson.frontmatter.audience,
  }))

  for (const item of planned) {
    // A curator's hand-written lesson at the same slug wins: the learning already ships, once.
    if (handWrittenPaths.has(item.path)) continue
    await mkdir(dirname(join(knowledgeDir, item.path)), { recursive: true })
    await writeFile(join(knowledgeDir, item.path), item.content, "utf8")
    written.push(`.harness/knowledge/${item.path}`)
    indexEntries.push({
      title: item.row.title,
      path: item.path,
      category: item.row.category,
      appliesTo: [],
      tags: [],
      evidenceCount: item.row.evidence.length,
      date: item.date,
      audience: item.row.audience,
    })
  }

  const index = knowledgeIndexFromLessons(indexEntries)
  await writeFile(join(knowledgeDir, "INDEX.md"), index, "utf8")
  written.push(".harness/knowledge/INDEX.md")
  return { written, pruned }
}

export type ProjectRef = { readonly id: string; readonly name: string }

/**
 * `--project` takes a name, a slug, or a raw id. Ids pass straight through; names and slugs
 * are resolved against the projects this token can see, so a typo fails loudly here instead
 * of silently writing every project's learnings into the repo.
 */
const resolveProjectFlag = async (
  deps: LearnDeps,
  input: string,
): Promise<ProjectRef | { readonly error: string }> => {
  if (UUID.test(input)) return { id: input, name: input }
  const res = await deps
    .fetch(`${deps.apiBase}/api/projects/resolve`, {
      headers: { authorization: `Bearer ${deps.token}` },
    })
    .catch(() => null)
  if (res === null) return { error: `Could not reach ${deps.apiBase}.` }
  if (!res.ok) return { error: `The server refused the project list (${res.status}).` }
  const body = (await res.json().catch(() => null)) as {
    projects?: ReadonlyArray<{ readonly id: string; readonly name: string; readonly slug: string }>
  }
  const projects = Array.isArray(body?.projects) ? body.projects : []
  const resolution = resolveOption({
    flag: "--project",
    input,
    options: projects.map((project) => ({
      value: project.id,
      names: [project.name, project.slug],
    })),
  })
  if (!resolution.ok) return { error: resolution.message }
  const matched = projects.find((project) => project.id === resolution.value)
  return { id: resolution.value, name: matched?.name ?? input }
}

const fetchLearnings = async (
  deps: LearnDeps,
  filters: { readonly projectId?: string; readonly audience?: string; readonly status?: string },
): Promise<ReadonlyArray<LearningRow> | { error: string }> => {
  const params = new URLSearchParams()
  if (filters.projectId !== undefined) params.set("projectId", filters.projectId)
  if (filters.audience === "agent" || filters.audience === "human") {
    params.set("audience", filters.audience)
  }
  const status =
    filters.status === "candidate" ||
    filters.status === "accepted" ||
    filters.status === "superseded"
      ? filters.status
      : undefined
  if (status !== undefined) params.set("status", status)
  else params.set("status", "accepted")

  const qs = params.toString()
  const res = await deps
    .fetch(`${deps.apiBase}/api/learnings${qs === "" ? "" : `?${qs}`}`, {
      headers: { authorization: `Bearer ${deps.token}` },
    })
    .catch(() => null)
  if (res === null) return { error: `Could not reach ${deps.apiBase}.` }
  if (!res.ok) return { error: `The server refused the learnings list (${res.status}).` }
  const body = (await res.json()) as { learnings: ReadonlyArray<LearningRow> }
  return body.learnings
}

export const learnCommand = async (
  options: LearnOptions & Partial<LearnDeps> = {},
): Promise<number> => {
  const deps: LearnDeps = {
    apiBase: options.apiBase ?? apiBase(),
    token: options.token ?? (await readToken()),
    fetch: options.fetch ?? globalThis.fetch,
    now: options.now,
    stdout: options.stdout,
  }
  const { stdout } = resolveIo({ stdout: deps.stdout })
  const now = (deps.now ?? (() => new Date()))()

  if (deps.token === null) {
    stdout.write(errorMessage("Not paired. Run `samskara login` first."))
    return 1
  }

  let projectId: string | undefined
  let projectName = "this project"
  if (options.project !== undefined) {
    const ref = await resolveProjectFlag(deps, options.project)
    if ("error" in ref) {
      stdout.write(`${errorMessage(ref.error)}\n`)
      return 1
    }
    projectId = ref.id
    projectName = ref.name
  }

  const rows = await fetchLearnings(deps, {
    projectId,
    audience: options.audience,
    status: options.status,
  })
  if (!Array.isArray(rows)) {
    const refusal = rows as { error: string }
    stdout.write(errorMessage(refusal.error))
    return 1
  }

  if (!options.write) {
    if (rows.length === 0) {
      stdout.write("No accepted learnings yet. Review sessions first, then accept learnings.\n")
      return 0
    }
    for (const row of rows) {
      stdout.write(
        `[${row.audience}] ${row.title} (${row.category}, seen ${row.occurrenceCount}x)\n  ${row.detail}\n`,
      )
    }
    stdout.write("\nWrite them into this repo with `samskara learn --write`.\n")
    return 0
  }

  const dir = options.out ?? process.cwd()
  const { written, pruned } = await writeLearnings(rows, { dir, projectName }, now)
  for (const path of written) stdout.write(`wrote ${path}\n`)
  for (const path of pruned) stdout.write(`pruned ${path}\n`)
  stdout.write(
    `\n${rows.length} accepted learning${rows.length === 1 ? "" : "s"} written. Regenerate any time; never hand-edit.\n`,
  )
  return 0
}
